export const FETCH_BARTENDERS_REQUEST = "FETCH_BARTENDERS_REQUEST";
export const FETCH_BARTENDERS_SUCCESS = "FETCH_BARTENDERS_SUCCESS";
export const FETCH_BARTENDERS_FAIL = "FETCH_BARTENDERS_FAIL";

export const FETCH_BARTENDERS_DETAILS_REQUEST =
  "FETCH_BARTENDERS_DETAILS_REQUEST";
export const FETCH_BARTENDERS_DETAILS_SUCCESS =
  "FETCH_BARTENDERS_DETAILS_SUCCESS";
export const FETCH_BARTENDERS_DETAILS_FAIL = "FETCH_BARTENDERS_DETAILS_FAIL";

export const SEND_MESSAGE_TO_BARTENDER_REQUEST =
  "SEND_MESSAGE_TO_BARTENDER_REQUEST";
export const SEND_MESSAGE_TO_BARTENDER_SUCCESS =
  "SEND_MESSAGE_TO_BARTENDER_SUCCESS";
export const SEND_MESSAGE_TO_BARTENDER_FAIL = "SEND_MESSAGE_TO_BARTENDER_FAIL";
export const RESET_BARTENDER_DETAILS = "RESET_BARTENDER_DETAILS";
