export const FETCH_BARTENDERS_REQUEST = "FETCH_BARTENDERS_REQUEST";
export const FETCH_BARTENDERS_SUCCESS = "FETCH_BARTENDERS_SUCCESS";
export const FETCH_BARTENDERS_FAIL = "FETCH_BARTENDERS_FAIL";

export const FETCH_BARTENDERS_DETAILS_REQUEST = "FETCH_BARTENDERS_DETAILS_REQUEST";
export const FETCH_BARTENDERS_DETAILS_SUCCESS = "FETCH_BARTENDERS_DETAILS_SUCCESS";
export const FETCH_BARTENDERS_DETAILS_FAIL = "FETCH_BARTENDERS_DETAILS_FAIL";