export const FETCH_LATEST_BLOG_POSTS_REQUEST = "FETCH_LATEST_BLOG_POSTS_REQUEST";
export const FETCH_LATEST_BLOG_POSTS_SUCCESS = "FETCH_LATEST_BLOG_POSTS_SUCCESS";
export const FETCH_LATEST_BLOG_POSTS_FAIL = "FETCH_LATEST_BLOG_POSTS_FAIL";