export const FETCH_BLOG_POSTS_REQUEST = "FETCH_BLOG_POSTS_REQUEST";
export const FETCH_BLOG_POSTS_SUCCESS = "FETCH_BLOG_POSTS_SUCCESS";
export const FETCH_BLOG_POSTS_FAIL = "FETCH_BLOG_POSTS_FAIL";

export const FETCH_LATEST_BLOG_POSTS_REQUEST =
  "FETCH_LATEST_BLOG_POSTS_REQUEST";
export const FETCH_LATEST_BLOG_POSTS_SUCCESS =
  "FETCH_LATEST_BLOG_POSTS_SUCCESS";
export const FETCH_LATEST_BLOG_POSTS_FAIL = "FETCH_LATEST_BLOG_POSTS_FAIL";

export const FETCH_BLOG_POST_DETAILS_REQUEST = "FETCH_BLOG_POST_DETAILS_REQUEST";
export const FETCH_BLOG_POST_DETAILS_SUCCESS = "FETCH_BLOG_POST_DETAILS_SUCCESS";
export const FETCH_BLOG_POST_DETAILS_FAIL = "FETCH_BLOG_POST_DETAILS_FAIL";
