export const FETCH_BLOG_POSTS_REQUEST = "FETCH_BLOG_POSTS_REQUEST";
export const FETCH_BLOG_POSTS_SUCCESS = "FETCH_BLOG_POSTS_SUCCESS";
export const FETCH_BLOG_POSTS_FAIL = "FETCH_BLOG_POSTS_FAIL";

export const FETCH_LATEST_BLOG_POSTS_REQUEST =
  "FETCH_LATEST_BLOG_POSTS_REQUEST";
export const FETCH_LATEST_BLOG_POSTS_SUCCESS =
  "FETCH_LATEST_BLOG_POSTS_SUCCESS";
export const FETCH_LATEST_BLOG_POSTS_FAIL = "FETCH_LATEST_BLOG_POSTS_FAIL";

export const FETCH_BLOG_POST_DETAILS_REQUEST =
  "FETCH_BLOG_POST_DETAILS_REQUEST";
export const FETCH_BLOG_POST_DETAILS_SUCCESS =
  "FETCH_BLOG_POST_DETAILS_SUCCESS";
export const FETCH_BLOG_POST_DETAILS_FAIL = "FETCH_BLOG_POST_DETAILS_FAIL";

export const SEND_BLOG_POST_REVIEW_REQUEST = "SEND_BLOG_POST_REVIEW_REQUEST";
export const SEND_BLOG_POST_REVIEW_SUCCESS = "SEND_BLOG_POST_REVIEW_SUCCESS";
export const SEND_BLOG_POST_REVIEW_FAIL = "SEND_BLOG_POST_REVIEW_FAIL";

export const LIKE_BLOG_POST_REVIEW_REQUEST = "LIKE_BLOG_POST_REVIEW_REQUEST";
export const LIKE_BLOG_POST_REVIEW_SUCCESS = "LIKE_BLOG_POST_REVIEW_SUCCESS";
export const LIKE_BLOG_POST_REVIEW_FAIL = "LIKE_BLOG_POST_REVIEW_FAIL";

export const DISLIKE_BLOG_POST_REVIEW_REQUEST =
  "DISLIKE_BLOG_POST_REVIEW_REQUEST";
export const DISLIKE_BLOG_POST_REVIEW_SUCCESS =
  "DISLIKE_BLOG_POST_REVIEW_SUCCESS";
export const DISLIKE_BLOG_POST_REVIEW_FAIL = "DISLIKE_BLOG_POST_REVIEW_FAIL";

export const RESET_BLOG_POST_DETAILS = "RESET_BLOG_POST_DETAILS";
