export const FETCH_RANDOM_COCKTAILS_REQUEST = "FETCH_RANDOM_COCKTAILS_REQUEST";
export const FETCH_RANDOM_COCKTAILS_SUCCESS = "FETCH_RANDOM_COCKTAILS_SUCCESS";
export const FETCH_RANDOM_COCKTAILS_FAIL = "FETCH_RANDOM_COCKTAILS_FAIL";

export const FETCH_COCKTAILS_LIST_REQUEST = "FETCH_COCKTAILS_LIST_REQUEST";
export const FETCH_COCKTAILS_LIST_SUCCESS = "FETCH_COCKTAILS_LIST_SUCCESS";
export const FETCH_COCKTAILS_LIST_FAIL = "FETCH_COCKTAILS_LIST_FAIL";

export const FETCH_COCKTAIL_DETAILS_REQUEST = "FETCH_COCKTAIL_DETAILS_REQUEST";
export const FETCH_COCKTAIL_DETAILS_SUCCESS = "FETCH_COCKTAIL_DETAILS_SUCCESS";
export const FETCH_COCKTAIL_DETAILS_FAIL = "FETCH_COCKTAIL_DETAILS_FAIL";