export const FETCH_RANDOM_COCKTAILS_REQUEST = "FETCH_RANDOM_COCKTAILS_REQUEST";
export const FETCH_RANDOM_COCKTAILS_SUCCESS = "FETCH_RANDOM_COCKTAILS_SUCCESS";
export const FETCH_RANDOM_COCKTAILS_FAIL = "FETCH_RANDOM_COCKTAILS_FAIL";