export const FETCH_RANDOM_COCKTAILS_REQUEST = "FETCH_RANDOM_COCKTAILS_REQUEST";
export const FETCH_RANDOM_COCKTAILS_SUCCESS = "FETCH_RANDOM_COCKTAILS_SUCCESS";
export const FETCH_RANDOM_COCKTAILS_FAIL = "FETCH_RANDOM_COCKTAILS_FAIL";

export const FETCH_COCKTAILS_LIST_REQUEST = "FETCH_COCKTAILS_LIST_REQUEST";
export const FETCH_COCKTAILS_LIST_SUCCESS = "FETCH_COCKTAILS_LIST_SUCCESS";
export const FETCH_COCKTAILS_LIST_FAIL = "FETCH_COCKTAILS_LIST_FAIL";

export const FETCH_COCKTAIL_DETAILS_REQUEST = "FETCH_COCKTAIL_DETAILS_REQUEST";
export const FETCH_COCKTAIL_DETAILS_SUCCESS = "FETCH_COCKTAIL_DETAILS_SUCCESS";
export const FETCH_COCKTAIL_DETAILS_FAIL = "FETCH_COCKTAIL_DETAILS_FAIL";

export const SEND_COCKTAIL_REVIEW_REQUEST = "SEND_COCKTAIL_REVIEW_REQUEST";
export const SEND_COCKTAIL_REVIEW_SUCCESS = "SEND_COCKTAIL_REVIEW_SUCCESS";
export const SEND_COCKTAIL_REVIEW_FAIL = "SEND_COCKTAIL_REVIEW_FAIL";

export const LIKE_COCKTAIL_REVIEW_REQUEST = "LIKE_COCKTAIL_REVIEW_REQUEST";
export const LIKE_COCKTAIL_REVIEW_SUCCESS = "LIKE_COCKTAIL_REVIEW_SUCCESS";
export const LIKE_COCKTAIL_REVIEW_FAIL = "LIKE_COCKTAIL_REVIEW_FAIL";

export const DISLIKE_COCKTAIL_REVIEW_REQUEST =
  "DISLIKE_COCKTAIL_REVIEW_REQUEST";
export const DISLIKE_COCKTAIL_REVIEW_SUCCESS =
  "DISLIKE_COCKTAIL_REVIEW_SUCCESS";
export const DISLIKE_COCKTAIL_REVIEW_FAIL = "DISLIKE_COCKTAIL_REVIEW_FAIL";

export const RESET_COCKTAIL_DETAILS = "RESET_COCKTAIL_DETAILS";
