export const FETCH_UPCOMING_EVENT_REQUEST = "FETCH_UPCOMING_EVENT_REQUEST";
export const FETCH_UPCOMING_EVENT_SUCCESS = "FETCH_UPCOMING_EVENT_SUCCESS";
export const FETCH_UPCOMING_EVENT_FAIL = "FETCH_UPCOMING_EVENT_FAIL";

export const FETCH_NEXT_EVENTS_REQUEST = "FETCH_NEXT_EVENTS_REQUEST";
export const FETCH_NEXT_EVENTS_SUCCESS = "FETCH_NEXT_EVENTS_SUCCESS";
export const FETCH_NEXT_EVENTS_FAIL = "FETCH_NEXT_EVENTS_FAIL";