export const FETCH_UPCOMING_EVENT_REQUEST = "FETCH_UPCOMING_EVENT_REQUEST";
export const FETCH_UPCOMING_EVENT_SUCCESS = "FETCH_UPCOMING_EVENT_SUCCESS";
export const FETCH_UPCOMING_EVENT_FAIL = "FETCH_UPCOMING_EVENT_FAIL";

export const FETCH_NEXT_EVENTS_REQUEST = "FETCH_NEXT_EVENTS_REQUEST";
export const FETCH_NEXT_EVENTS_SUCCESS = "FETCH_NEXT_EVENTS_SUCCESS";
export const FETCH_NEXT_EVENTS_FAIL = "FETCH_NEXT_EVENTS_FAIL";

export const FETCH_EVENTS_LIST_REQUEST = "FETCH_EVENTS_LIST_REQUEST";
export const FETCH_EVENTS_LIST_SUCCESS = "FETCH_EVENTS_LIST_SUCCESS";
export const FETCH_EVENTS_LIST_FAIL = "FETCH_EVENTS_LIST_FAIL";

export const FETCH_EVENT_DETAILS_REQUEST = "FETCH_EVENT_DETAILS_REQUEST";
export const FETCH_EVENT_DETAILS_SUCCESS = "FETCH_EVENT_DETAILS_SUCCESS";
export const FETCH_EVENT_DETAILS_FAIL = "FETCH_EVENT_DETAILS_FAIL";
