export const FETCH_UPCOMING_EVENT_REQUEST = "FETCH_UPCOMING_EVENT_REQUEST";
export const FETCH_UPCOMING_EVENT_SUCCESS = "FETCH_UPCOMING_EVENT_SUCCESS";
export const FETCH_UPCOMING_EVENT_FAIL = "FETCH_UPCOMING_EVENT_FAIL";
