export const FETCH_INSTAGRAM_PHOTOS_REQUEST = "FETCH_INSTAGRAM_PHOTOS_REQUEST";
export const FETCH_INSTAGRAM_PHOTOS_SUCCESS = "FETCH_INSTAGRAM_PHOTOS_SUCCESS";
export const FETCH_INSTAGRAM_PHOTOS_FAIL = "FETCH_INSTAGRAM_PHOTOS_FAIL";

export const FETCH_GALLERY_PHOTOS_REQUEST = "FETCH_GALLERY_PHOTOS_REQUEST";
export const FETCH_GALLERY_PHOTOS_SUCCESS = "FETCH_GALLERY_PHOTOS_SUCCESS";
export const FETCH_GALLERY_PHOTOS_FAIL = "FETCH_GALLERY_PHOTOS_FAIL";
