const USER_LOGIN = "USER_LOGIN";
const USER_LOGOUT = "USER_LOGOUT";
const LOAD_USERS = "LOAD_USERS";
const LOAD_EVENTS = "LOAD_EVENTS";
const LOAD_BLOG_POSTS = "LOAD_BLOG_POSTS";
const LOAD_REVIEWS = "LOAD_REVIEWS";
const ADD_REVIEW = "ADD_REVIEW";
const DELETE_REVIEW = "DELETE_REVIEW";
const EDIT_REVIEW = "EDIT_REVIEW";
const USER_LOG_IN = "USER_LOG_IN";
const USER_LOG_OUT = "USER_LOG_OUT";
const START = "START";
const SUCCESS = "SUCCESS";
const FAIL = "FAIL";

export {
    USER_LOGIN,
    USER_LOGOUT,
    LOAD_USERS,
    LOAD_EVENTS,
    LOAD_BLOG_POSTS,
    LOAD_REVIEWS,
    ADD_REVIEW,
    DELETE_REVIEW,
    EDIT_REVIEW,
    USER_LOG_IN,
    USER_LOG_OUT,
    START,
    SUCCESS,
    FAIL
};