const LOAD_USERS = "LOAD_USERS";
const LOAD_EVENTS = "LOAD_EVENTS";
const LOAD_BLOG_POSTS = "LOAD_BLOG_POSTS";
const LOAD_BLOG_POSTS_REVIEWS = "LOAD_BLOG_POSTS_REVIEWS";
const LOAD_BARTENDERS = "LOAD_BARTENDERS";
const LOAD_BARTENDER_BY_ID = "LOAD_BARTENDER_BY_ID";
const LOAD_EVENT_BY_ID = "LOAD_EVENT_BY_ID";
const LOAD_BLOG_POST_BY_ID = "LOAD_BLOG_POST_BY_ID";
const ADD_REVIEW_FOR_BLOG_POST = "ADD_REVIEW_FOR_BLOG_POST";
const DELETE_REVIEW = "DELETE_REVIEW";
const CREATE_NEW_USER = "CREATE_NEW_USER";
const EDIT_REVIEW = "EDIT_REVIEW";
const USER_LOG_IN = "USER_LOG_IN";
const USER_LOG_OUT = "USER_LOG_OUT";
const START = "_START";
const SUCCESS = "_SUCCESS";
const FAIL = "_FAIL";
const LOAD_RANDOM_COCKTAILS = "LOAD_RANDOM_COCKTAILS";

export {
    LOAD_USERS,
    LOAD_EVENTS,
    LOAD_BLOG_POSTS,
    LOAD_BLOG_POSTS_REVIEWS,
    LOAD_BARTENDERS,
    LOAD_BARTENDER_BY_ID,
    LOAD_EVENT_BY_ID,
    LOAD_BLOG_POST_BY_ID,
    ADD_REVIEW_FOR_BLOG_POST,
    CREATE_NEW_USER,
    DELETE_REVIEW,
    EDIT_REVIEW,
    USER_LOG_IN,
    USER_LOG_OUT,
    LOAD_RANDOM_COCKTAILS,
    START,
    SUCCESS,
    FAIL
};