const LOAD_USERS = "LOAD_USERS";
const LOAD_EVENTS = "LOAD_EVENTS";
const LOAD_BLOG_POSTS = "LOAD_BLOG_POSTS";
const LOAD_REVIEWS = "LOAD_REVIEWS";
const LOAD_BARTENDERS = "LOAD_BARTENDERS";
const ADD_REVIEW = "ADD_REVIEW";
const DELETE_REVIEW = "DELETE_REVIEW";
const EDIT_REVIEW = "EDIT_REVIEW";
const USER_LOG_IN = "USER_LOG_IN";
const USER_LOG_OUT = "USER_LOG_OUT";
const START = "_START";
const SUCCESS = "_SUCCESS";
const FAIL = "_FAIL";

export {
    LOAD_USERS,
    LOAD_EVENTS,
    LOAD_BLOG_POSTS,
    LOAD_REVIEWS,
    LOAD_BARTENDERS,
    ADD_REVIEW,
    DELETE_REVIEW,
    EDIT_REVIEW,
    USER_LOG_IN,
    USER_LOG_OUT,
    START,
    SUCCESS,
    FAIL
};