export const FETCH_USER_INFO_REQUEST = "FETCH_USER_INFO_REQUEST";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_FAIL = "FETCH_USER_INFO_FAIL";

export const USER_SEND_MESSAGE_REQUEST = "USER_SEND_MESSAGE_REQUEST";
export const USER_SEND_MESSAGE_SUCCESS = "USER_SEND_MESSAGE_SUCCESS";
export const USER_SEND_MESSAGE_FAIL = "USER_SEND_MESSAGE_FAIL";

export const ADD_ITEM_TO_CARD_REQUEST = "ADD_ITEM_TO_CARD_REQUEST";
export const ADD_ITEM_TO_CARD_SUCCESS = "ADD_ITEM_TO_CARD_SUCCESS";
export const ADD_ITEM_TO_CARD_FAIL = "ADD_ITEM_TO_CARD_FAIL";

export const DELETE_ITEM_FROM_CARD_REQUEST = "DELETE_ITEM_FROM_CARD_REQUEST";
export const DELETE_ITEM_FROM_CARD_SUCCESS = "DELETE_ITEM_FROM_CARD_SUCCESS";
export const DELETE_ITEM_FROM_CARD_FAIL = "DELETE_ITEM_FROM_CARD_FAIL";

export const ADD_ITEM_TO_WISH_LIST_REQUEST = "ADD_ITEM_TO_WISH_LIST_REQUEST";
export const ADD_ITEM_TO_WISH_LIST_SUCCESS = "ADD_ITEM_TO_WISH_LIST_SUCCESS";
export const ADD_ITEM_TO_WISH_LIST_FAIL = "ADD_ITEM_TO_WISH_LIST_FAIL";

export const DELETE_ITEM_FROM_WISH_LIST_REQUEST = "DELETE_ITEM_FROM_WISH_LIST_REQUEST";
export const DELETE_ITEM_FROM_WISH_LIST_SUCCESS = "DELETE_ITEM_FROM_WISH_LIST_SUCCESS";
export const DELETE_ITEM_FROM_WISH_LIST_FAIL = "DELETE_ITEM_FROM_WISH_LIST_FAIL";