export const FETCH_USER_INFO_REQUEST = "FETCH_USER_INFO_REQUEST";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_FAIL = "FETCH_USER_INFO_FAIL";

export const USER_SEND_MESSAGE_REQUEST = "USER_SEND_MESSAGE_REQUEST";
export const USER_SEND_MESSAGE_SUCCESS = "USER_SEND_MESSAGE_SUCCESS";
export const USER_SEND_MESSAGE_FAIL = "USER_SEND_MESSAGE_FAIL";

export const ADD_ITEM_TO_CARD = "ADD_ITEM_TO_CARD";
export const DELETE_ITEM_FROM_CARD = "DELETE_ITEM_FROM_CARD";

export const ADD_ITEM_TO_WISH_LIST = "ADD_ITEM_TO_WISH_LIST";
export const DELETE_ITEM_FROM_WISH_LIST = "DELETE_ITEM_FROM_WISH_LIST";