type ParamItemType = {
  label: string;
  value: string;
};

export const ALCOHOLIC: ParamItemType[] = [
  { label: "Alcoholic", value: "Alcoholic" },
  { label: "Non alcoholic", value: "Non alcoholic" },
  { label: "Optional alcohol", value: "Optional alcohol" },
];

export const CATEGORIES: ParamItemType[] = [
  { label: "Beer", value: "Beer" },
  { label: "Cocktail", value: "Cocktail" },
  { label: "Cocoa", value: "Cocoa" },
  { label: "Coffee / Tea", value: "Coffee Tea" },
  { label: "Homemade Liqueur", value: "Homemade Liqueur" },
  { label: "Milk Float Shake", value: "Milk Float Shake" },
  { label: "Ordinary Drink", value: "Ordinary Drink" },
  { label: "Other/Unknown", value: "Other/Unknown" },
  { label: "Punch Party Drink", value: "Punch Party Drink" },
  { label: "Shot", value: "Shot" },
  { label: "Soft Drink Soda", value: "Soft Drink Soda" },
];

export const INGREDIENTS: ParamItemType[] = [
  { label: "151 proof rum", value: "151 proof rum" },
  { label: "7-up", value: "7-up" },
  { label: "Absolut citron", value: "absolut citron" },
  { label: "Absolut kurant", value: "absolut kurant" },
  { label: "Absolut vodka", value: "absolut vodka" },
  { label: "Allspice", value: "allspice" },
  { label: "Almond", value: "almond" },
  { label: "Almond flavoring", value: "almond flavoring" },
  { label: "Amaretto", value: "amaretto" },
  { label: "Angelica root", value: "angelica root" },
  { label: "Angostura bitters", value: "angostura bitters" },
  { label: "Anise", value: "anise" },
  { label: "Apple", value: "apple" },
  { label: "Apple brandy", value: "apple brandy" },
  { label: "Apple cider", value: "apple cider" },
  { label: "Apple juice", value: "apple juice" },
  { label: "Apple schnapps", value: "apple schnapps" },
  { label: "Applejack", value: "applejack" },
  { label: "Apricot", value: "apricot" },
  { label: "Apricot brandy", value: "apricot brandy" },
  { label: "Asafoetida", value: "asafoetida" },
  { label: "Añejo rum", value: "añejo rum" },
  { label: "Baileys irish cream", value: "baileys irish cream" },
  { label: "Banana", value: "banana" },
  { label: "Banana liqueur", value: "banana liqueur" },
  { label: "Benedictine", value: "benedictine" },
  { label: "Berries", value: "berries" },
  { label: "Bitter lemon", value: "bitter lemon" },
  { label: "Bitters", value: "bitters" },
  { label: "Black pepper", value: "black pepper" },
  { label: "Blackberry brandy", value: "blackberry brandy" },
  { label: "Blended whiskey", value: "blended whiskey" },
  { label: "Blue curacao", value: "blue curacao" },
  { label: "Blueberry schnapps", value: "blueberry schnapps" },
  { label: "Bourbon", value: "bourbon" },
  { label: "Brandy", value: "brandy" },
  { label: "Brown sugar", value: "brown sugar" },
  { label: "Butter", value: "butter" },
  { label: "Campari", value: "campari" },
  { label: "Candy", value: "candy" },
  { label: "Cantaloupe", value: "cantaloupe" },
  { label: "Carbonated soft drink", value: "carbonated soft drink" },
  { label: "Cardamom", value: "cardamom" },
  { label: "Carrot", value: "carrot" },
  { label: "Cayenne pepper", value: "cayenne pepper" },
  { label: "Celery salt", value: "celery salt" },
  { label: "Chambord raspberry liqueur", value: "chambord raspberry liqueur" },
  { label: "Champagne", value: "champagne" },
  { label: "Cherry", value: "cherry" },
  { label: "Chocolate", value: "chocolate" },
  { label: "Chocolate ice-cream", value: "chocolate ice-cream" },
  { label: "Chocolate milk", value: "chocolate milk" },
  { label: "Chocolate syrup", value: "chocolate syrup" },
  { label: "Cider", value: "cider" },
  { label: "Cinnamon", value: "cinnamon" },
  { label: "Cloves", value: "cloves" },
  { label: "Club soda", value: "club soda" },
  { label: "Coca-cola", value: "coca-cola" },
  { label: "Cocoa powder", value: "cocoa powder" },
  { label: "Coconut liqueur", value: "coconut liqueur" },
  { label: "Coconut rum", value: "coconut rum" },
  { label: "Coffee", value: "coffee" },
  { label: "Cognac", value: "cognac" },
  { label: "Cointreau", value: "cointreau" },
  { label: "Condensed milk", value: "condensed milk" },
  { label: "Coriander", value: "coriander" },
  { label: "Cornstarch", value: "cornstarch" },
  { label: "Cranberry juice", value: "cranberry juice" },
  { label: "Cream", value: "cream" },
  { label: "Creme de banane", value: "creme de banane" },
  { label: "Creme de cacao", value: "creme de cacao" },
  { label: "Creme de cassis", value: "creme de cassis" },
  { label: "Cumin seed", value: "cumin seed" },
  { label: "Dark creme de cacao", value: "dark creme de cacao" },
  { label: "Dark rum", value: "dark rum" },
  { label: "Dry vermouth", value: "dry vermouth" },
  { label: "Egg", value: "egg" },
  { label: "Egg white", value: "egg white" },
  { label: "Egg yolk", value: "egg yolk" },
  { label: "Espresso", value: "espresso" },
  { label: "Food coloring", value: "food coloring" },
  { label: "Frangelico", value: "frangelico" },
  { label: "Fresh lemon juice", value: "fresh lemon juice" },
  { label: "Fresh lime juice", value: "fresh lime juice" },
  { label: "Fruit", value: "fruit" },
  { label: "Fruit juice", value: "fruit juice" },
  { label: "Galliano", value: "galliano" },
  { label: "Gin", value: "gin" },
  { label: "Ginger", value: "ginger" },
  { label: "Ginger ale", value: "ginger ale" },
  { label: "Ginger beer", value: "ginger beer" },
  { label: "Goldschlager", value: "goldschlager" },
  { label: "Grain alcohol", value: "grain alcohol" },
  { label: "Grand marnier", value: "grand marnier" },
  { label: "Grape juice", value: "grape juice" },
  { label: "Grape soda", value: "grape soda" },
  { label: "Grapefruit juice", value: "grapefruit juice" },
  { label: "Grapes", value: "grapes" },
  { label: "Green creme de menthe", value: "green creme de menthe" },
  { label: "Grenadine", value: "grenadine" },
  { label: "Guava juice", value: "guava juice" },
  { label: "Half-and-half", value: "half-and-half" },
  { label: "Heavy cream", value: "heavy cream" },
  { label: "Honey", value: "honey" },
  { label: "Hot chocolate", value: "hot chocolate" },
  { label: "Hpnotiq", value: "hpnotiq" },
  { label: "Ice", value: "ice" },
  { label: "Jack daniels", value: "jack daniels" },
  { label: "Jim beam", value: "jim beam" },
  { label: "Johnnie walker", value: "johnnie walker" },
  { label: "Jägermeister", value: "jägermeister" },
  { label: "Kahlua", value: "kahlua" },
  { label: "Kirschwasser", value: "kirschwasser" },
  { label: "Kiwi", value: "kiwi" },
  { label: "Kummel", value: "kummel" },
  { label: "Lager", value: "lager" },
  { label: "Lemon", value: "lemon" },
  { label: "Lemon juice", value: "lemon juice" },
  { label: "Lemon peel", value: "lemon peel" },
  { label: "Lemon vodka", value: "lemon vodka" },
  { label: "Lemon-lime soda", value: "lemon-lime soda" },
  { label: "Lemonade", value: "lemonade" },
  { label: "Licorice root", value: "licorice root" },
  { label: "Light cream", value: "light cream" },
  { label: "Light rum", value: "light rum" },
  { label: "Lime", value: "lime" },
  { label: "Lime juice", value: "lime juice" },
  { label: "Lime peel", value: "lime peel" },
  { label: "Malibu rum", value: "malibu rum" },
  { label: "Mango", value: "mango" },
  { label: "Maraschino cherry", value: "maraschino cherry" },
  { label: "Marjoram leaves", value: "marjoram leaves" },
  { label: "Marshmallows", value: "marshmallows" },
  { label: "Maui", value: "maui" },
  { label: "Midori melon liqueur", value: "midori melon liqueur" },
  { label: "Milk", value: "milk" },
  { label: "Mint", value: "mint" },
  { label: "Mint syrup", value: "mint syrup" },
  { label: "Mountain dew", value: "mountain dew" },
  { label: "Nutmeg", value: "nutmeg" },
  { label: "Orange", value: "orange" },
  { label: "Orange bitters", value: "orange bitters" },
  { label: "Orange curacao", value: "orange curacao" },
  { label: "Orange juice", value: "orange juice" },
  { label: "Orange peel", value: "orange peel" },
  { label: "Papaya", value: "papaya" },
  { label: "Passion fruit juice", value: "passion fruit juice" },
  { label: "Peach nectar", value: "peach nectar" },
  { label: "Peach schnapps", value: "peach schnapps" },
  { label: "Peach vodka", value: "peach vodka" },
  { label: "Peppermint schnapps", value: "peppermint schnapps" },
  { label: "Pineapple", value: "pineapple" },
  { label: "Pineapple juice", value: "pineapple juice" },
  { label: "Pisang ambon", value: "pisang ambon" },
  { label: "Red wine", value: "red wine" },
  { label: "Roses sweetened lime juice", value: "roses sweetened lime juice" },
  { label: "Rum", value: "rum" },
  { label: "Rumple minze", value: "rumple minze" },
  { label: "Salt", value: "salt" },
  { label: "Schweppes russchian", value: "schweppes russchian" },
  { label: "Scotch", value: "scotch" },
  { label: "Sherbet", value: "sherbet" },
  { label: "Sherry", value: "sherry" },
  { label: "Sloe gin", value: "sloe gin" },
  { label: "Soda water", value: "soda water" },
  { label: "Sour mix", value: "sour mix" },
  { label: "Southern comfort", value: "southern comfort" },
  { label: "Sprite", value: "sprite" },
  { label: "Strawberries", value: "strawberries" },
  { label: "Strawberry liqueur", value: "strawberry liqueur" },
  { label: "Strawberry schnapps", value: "strawberry schnapps" },
  { label: "Sugar", value: "sugar" },
  { label: "Sugar syrup", value: "sugar syrup" },
  { label: "Sweet and sour", value: "sweet and sour" },
  { label: "Sweet vermouth", value: "sweet vermouth" },
  { label: "Tea", value: "tea" },
  { label: "Tequila", value: "tequila" },
  { label: "Tomato juice", value: "tomato juice" },
  { label: "Tonic water", value: "tonic water" },
  { label: "Triple sec", value: "triple sec" },
  { label: "Vanilla", value: "vanilla" },
  { label: "Vanilla extract", value: "vanilla extract" },
  { label: "Vanilla ice-cream", value: "vanilla ice-cream" },
  { label: "Vanilla vodka", value: "vanilla vodka" },
  { label: "Vermouth", value: "vermouth" },
  { label: "Vodka", value: "vodka" },
  { label: "Water", value: "water" },
  { label: "Whipped cream", value: "whipped cream" },
  { label: "Whipping cream", value: "whipping cream" },
  { label: "White creme de menthe", value: "white creme de menthe" },
  { label: "White wine", value: "white wine" },
  { label: "Wild turkey", value: "wild turkey" },
  { label: "Wine", value: "wine" },
  { label: "Wormwood", value: "wormwood" },
  { label: "Yellow chartreuse", value: "yellow chartreuse" },
  { label: "Yoghurt", value: "yoghurt" },
];
